-- Synthetic financial evidence only. Transaction rolls back all fixtures.
begin;
create extension if not exists pgtap with schema extensions;
select no_plan();
create function pg_temp.act_as(uid text) returns void language sql as $$
select set_config('request.jwt.claims',json_build_object('sub',uid,'role','authenticated')::text,true);
$$;
insert into identity.contacts(id,workspace_id,display_name) values('bbbbbbbb-3309-0000-0000-000000000001','11111111-1111-1111-1111-111111111111','Synthetic sale customer');
insert into sales.leads(id,workspace_id,contact_id,source_channel,raw_name,owner_id,created_at) values
('cccccccc-3309-0000-0000-000000000001','11111111-1111-1111-1111-111111111111','bbbbbbbb-3309-0000-0000-000000000001','tiktok','Synthetic sale inquiry','aaaaaaaa-0000-0000-0000-000000000004',now()-interval '3 days');
insert into sales.tasks(workspace_id,lead_id,title,assignee_id,due_at) values('11111111-1111-1111-1111-111111111111','cccccccc-3309-0000-0000-000000000001','Synthetic open followup','aaaaaaaa-0000-0000-0000-000000000004',now());
create temp table result(id uuid); grant all on result to authenticated;
create function pg_temp.reject_financial_history() returns trigger language plpgsql as $$
begin
  if new.body='Synthetic financial failure' then raise exception 'Synthetic financial failure'; end if;
  return new;
end $$;
create trigger reject_financial_history before insert on sales.activities for each row execute function pg_temp.reject_financial_history();
create function pg_temp.input(extra jsonb default '{}') returns jsonb language sql as $$
select jsonb_build_object('lead_id','cccccccc-3309-0000-0000-000000000001','external_ref','F3-SYNTHETIC-001','document_type','invoice','occurred_at',now()-interval '2 days','gross_before_discount',1000,'discount_amount',100,'tax_amount',54)||extra;
$$;
create function pg_temp.cmd(action text,extra jsonb default '{}',request uuid default gen_random_uuid()) returns uuid language sql as $$
select api.sale_command(action,jsonb_build_object('purchase_id',p.id,'version',p.version,'occurred_at',now()-interval '1 hour','reason','Synthetic verification')||extra,request)
from api.purchases p join result r on r.id=p.id;
$$;
set local role authenticated;
select pg_temp.act_as('aaaaaaaa-0000-0000-0000-000000000005');
insert into result select api.sale_command('save',pg_temp.input(),'dddddddd-3309-0000-0000-000000000001');
select is(api.sale_command('save',pg_temp.input(),'dddddddd-3309-0000-0000-000000000001'),(select id from result),'creation retry reuses the sale');
select throws_ok($$select api.sale_command('save',pg_temp.input('{"tax_amount":55}'),'dddddddd-3309-0000-0000-000000000001')$$,'23514','Retry differs from original command','retry payload protected');
select is((select financial_state from api.purchases p join result using(id)),'pending_evidence','draft state');
select is((select amount from api.purchases p join result using(id)),0::numeric,'draft excluded from old monetary sums');
select is((select net_sales from api.sale_balances p join result using(id)),0::numeric,'draft is not revenue');
select is((select confirmed_sales from api.inbox_leads where id='cccccccc-3309-0000-0000-000000000001'),0::bigint,'draft does not close inquiry');
select throws_ok($$select pg_temp.cmd('confirm')$$,'23514','Upload the receipt or invoice before confirming this sale','evidence required');
select throws_ok($$select api.sale_command('save',pg_temp.input(),gen_random_uuid())$$,'23514','Document already recorded. Open and review the existing purchase instead.','same document not double recorded');
select throws_ok($$select pg_temp.cmd('save',pg_temp.input('{"tax_amount":null}'))$$,'23514','Enter a document, positive sale before tax, discount and explicitly stated tax (zero if none)','unknown tax rejected');
select throws_ok($$select pg_temp.cmd('save',pg_temp.input('{"gross_before_discount":"NaN"}'))$$,'23514','Enter a document, positive sale before tax, discount and explicitly stated tax (zero if none)','nonfinite money rejected');
select throws_ok($$update api.purchases set amount=1 where id=(select id from result)$$,'42501',null,'direct financial mutation denied');
select lives_ok($$select api.prepare_sale_receipt((select id from result),'eeeeeeee-3309-0000-0000-000000000001','synthetic.pdf','application/pdf',100)$$,'prepare private evidence');
select throws_ok($$select pg_temp.cmd('confirm')$$,'23514','Upload the receipt or invoice before confirming this sale','upload intent alone is insufficient');
select throws_ok($$select api.prepare_sale_receipt((select id from result),gen_random_uuid(),'bad.svg','image/svg+xml',100)$$,'23514','Choose a PDF, JPG or PNG up to 5 MB','active image type rejected');
select throws_ok($$select api.prepare_sale_receipt((select id from result),gen_random_uuid(),'huge.pdf','application/pdf',5242881)$$,'23514','Choose a PDF, JPG or PNG up to 5 MB','oversize evidence rejected');
reset role;
insert into storage.objects(bucket_id,name,metadata) select 'sales-receipts',object_path,'{"size":100,"mimetype":"application/pdf"}' from sales.sale_receipts where id='eeeeeeee-3309-0000-0000-000000000001';
set local role authenticated;
select lives_ok($$select pg_temp.cmd('confirm')$$,'confirm documented sale');
select is((select net_sales from api.sale_balances p join result using(id)),900::numeric,'revenue excludes discounts and tax');
select is((select amount from api.purchases p join result using(id)),954::numeric,'document total retains tax');
select is((select confirmed_sales from api.inbox_leads where id='cccccccc-3309-0000-0000-000000000001'),1::bigint,'one closed inquiry');
select is((api.inquiry_page('won')->>'total')::int,1,'closed view includes the inquiry');
select is((select needs_action from api.inbox_leads where id='cccccccc-3309-0000-0000-000000000001'),false,'closed inquiry leaves action queue');
reset role;
select is((select count(*) from sales.tasks where lead_id='cccccccc-3309-0000-0000-000000000001' and status='open'),0::bigint,'sale closes pending reminders across owner boundary');
set local role authenticated;
select is((select source_channel from api.leads where id='cccccccc-3309-0000-0000-000000000001'),'tiktok','original source preserved');
select lives_ok($$select pg_temp.cmd('collection','{"amount":200,"method":"bank_transfer"}')$$,'partial deposit accepted');
select is((select net_sales from api.sale_balances p join result using(id)),900::numeric,'deposit does not create revenue');
select is((select collections from api.sale_balances p join result using(id)),200::numeric,'deposit changes collections');
select is((select balance_due from api.sale_balances p join result using(id)),754::numeric,'balance includes tax less deposit');
select throws_ok($$select pg_temp.cmd('collection','{"amount":1,"method":"cash","reason":"Synthetic financial failure"}')$$,'P0001','Synthetic financial failure','financial history failure aborts transaction');
select is((select collections from api.sale_balances p join result using(id)),200::numeric,'aborted transaction leaves collections unchanged');
select is((select count(*) from api.feedback_purchase_context((select id from result))),1::bigint,'confirmed sale remains available to feedback workflow');
select pg_temp.act_as('aaaaaaaa-0000-0000-0000-000000000002');
create temp table older_collection(id uuid); grant all on older_collection to authenticated;
insert into older_collection select api.record_purchase('bbbbbbbb-3309-0000-0000-000000000001',null,50,'F3-OLD-DEPOSIT','[{"method":"cash","amount":50}]');
select lives_ok($$select api.sale_command('collection_only',jsonb_build_object('purchase_id',p.id,'version',p.version,'collection_parent_id',(select id from result),'reason','Verified deposit belongs to full invoice'),gen_random_uuid()) from api.purchases p join older_collection using(id)$$,'historical collection can link to canonical sale');
select is((select collection_parent_id from api.purchases p join older_collection using(id)),(select id from result),'source receipt points to canonical sale');
select is((select count(*) from api.purchase_payments where purchase_id=(select id from older_collection)),0::bigint,'payment rows move instead of copy');
select is((select unreviewed_payments from api.sale_balances p join result using(id)),1::bigint,'moved payment awaits verification');
select is((select collections from api.sale_balances p join result using(id)),200::numeric,'linking receipt does not invent verified collection');
select throws_ok($$select api.sale_command('collection',jsonb_build_object('purchase_id',p.id,'version',p.version,'amount',50,'method','cash','reason','Synthetic duplicate'),gen_random_uuid()) from api.purchases p join older_collection using(id)$$,'23514','Record payments on the linked full sale','linked collection receipt cannot collect twice');
select pg_temp.act_as('aaaaaaaa-0000-0000-0000-000000000005');
select throws_ok($$select pg_temp.cmd('collection','{"amount":755,"method":"cash"}')$$,'23514','Collection exceeds the remaining document balance','overcollection rejected');
select throws_ok($$select pg_temp.cmd('collection','{"amount":100,"method":"credit_terms"}')$$,'23514','Choose a reviewed sale, actual payment method, valid amount/date and reference or reason; credit terms are not cash','credit terms are not collections');
select throws_ok($$select pg_temp.cmd('credit','{"amount":100,"tax_amount":6}')$$,'42501',null,'showroom cannot credit revenue');
select pg_temp.act_as('aaaaaaaa-0000-0000-0000-000000000002');
select throws_ok($$select pg_temp.cmd('credit','{"amount":100,"tax_amount":6}')$$,'23514','Upload and select supporting evidence for the adjustment','adjustment evidence required');
select lives_ok($$select pg_temp.cmd('credit','{"amount":100,"tax_amount":6,"evidence_id":"eeeeeeee-3309-0000-0000-000000000001"}')$$,'dated revenue credit accepted');
select is((select net_sales from api.sale_balances p join result using(id)),800::numeric,'credit reduces net revenue');
select is((select collections from api.sale_balances p join result using(id)),200::numeric,'credit does not invent cash refund');
select throws_ok($$select pg_temp.cmd('refund','{"amount":1,"method":"cash"}')$$,'23514','Upload and select supporting evidence for the cash refund','refund requires evidence');
select throws_ok($$select pg_temp.cmd('refund','{"amount":201,"method":"cash"}')$$,'23514','Cash refund exceeds recorded collections','excess cash refund rejected');
select lives_ok($$select pg_temp.cmd('refund','{"amount":50,"method":"cash","evidence_id":"eeeeeeee-3309-0000-0000-000000000001"}')$$,'cash refund accepted');
select is((select collections from api.sale_balances p join result using(id)),150::numeric,'cash refund changes collections');
select lives_ok($$select pg_temp.cmd('void','{"evidence_id":"eeeeeeee-3309-0000-0000-000000000001"}')$$,'void reverses remaining revenue');
select is((select net_sales from api.sale_balances p join result using(id)),0::numeric,'void leaves zero cumulative revenue');
select is((select collections from api.sale_balances p join result using(id)),150::numeric,'void does not remove money received');
select is((select confirmed_sales from api.inbox_leads where id='cccccccc-3309-0000-0000-000000000001'),0::bigint,'void removes closed-sale milestone');
select is((select needs_action from api.inbox_leads where id='cccccccc-3309-0000-0000-000000000001'),true,'void surfaces next-action gap');
select throws_ok($$select pg_temp.cmd('collection','{"amount":1,"method":"cash"}')$$,'23514','Collection exceeds the remaining document balance','voided sale cannot collect more');
select lives_ok($$select pg_temp.cmd('refund','{"amount":150,"method":"cash","evidence_id":"eeeeeeee-3309-0000-0000-000000000001"}')$$,'remaining money can be refunded after void');
select throws_ok($$select pg_temp.cmd('save',pg_temp.input())$$,'23514','Confirmed values are immutable; record a credit or void instead','confirmed value cannot be overwritten');
select throws_ok($$select pg_temp.cmd('refund','{"amount":1,"method":"cash","version":1}')$$,'40001','Sale changed. Refresh before saving.','stale edits rejected');
-- Legacy amounts and payments require explicit, independent review.
create temp table legacy(id uuid); grant all on legacy to authenticated;
insert into legacy select api.record_purchase('bbbbbbbb-3309-0000-0000-000000000001',null,400,'F3-LEGACY','[{"method":"cash","amount":100},{"method":"credit_terms","amount":300}]');
select is((select net_sales from api.sale_balances p join legacy using(id)),0::numeric,'historical value is not inferred as revenue');
select is((select collections from api.sale_balances p join legacy using(id)),0::numeric,'historical cash remains unreviewed');
select lives_ok($$select api.sale_command('collection_only',jsonb_build_object('purchase_id',p.id,'version',p.version,'reason','Verified original collection receipt'),gen_random_uuid()) from api.purchases p join legacy using(id)$$,'classify historical collection');
select lives_ok($$select api.sale_command('review_payment',jsonb_build_object('purchase_id',p.id,'version',p.version,'payment_id',pp.id,'occurred_at',now(),'reason','Verified bank and original receipt'),gen_random_uuid()) from api.purchases p join legacy using(id) join api.purchase_payments pp on pp.purchase_id=p.id and pp.method='cash'$$,'review historical actual payment');
select is((select collections from api.sale_balances p join legacy using(id)),100::numeric,'review includes only verified cash');
select is((select net_sales from api.sale_balances p join legacy using(id)),0::numeric,'collection-only record has no revenue');
select throws_ok($$select api.sale_command('review_payment',jsonb_build_object('purchase_id',p.id,'version',p.version,'payment_id',pp.id,'occurred_at',now(),'reason','Synthetic review'),gen_random_uuid()) from api.purchases p join legacy using(id) join api.purchase_payments pp on pp.purchase_id=p.id and pp.method='credit_terms'$$,'23514','Choose a reviewed sale, actual payment method, valid amount/date and reference or reason; credit terms are not cash','legacy credit terms cannot be accepted as cash');
select throws_ok($$select api.sale_command('collection_only',jsonb_build_object('purchase_id',p.id,'version',p.version,'collection_parent_id',(select id from result),'reason','Synthetic link'),gen_random_uuid()) from api.purchases p join legacy using(id)$$,'23514','Choose a confirmed sale for the same customer; collection records can be linked once','cannot attach collection to a voided sale');
reset role;
insert into core.workspaces(id,slug,name) values('99999999-3309-0000-0000-000000000099','f3-isolation','Synthetic foreign workspace');
insert into sales.purchases(id,workspace_id,amount) values('bbbbbbbb-3309-0000-0000-000000000099','99999999-3309-0000-0000-000000000099',100);
set local role authenticated;
select throws_ok($$select api.sale_command('correct_legacy','{"purchase_id":"bbbbbbbb-3309-0000-0000-000000000099","version":1,"amount":500,"reason":"Synthetic cross tenant attempt"}',gen_random_uuid())$$,'42501','Sale not found','cross-workspace mutation blocked');
select throws_ok($$select api.prepare_sale_receipt('bbbbbbbb-3309-0000-0000-000000000099',gen_random_uuid(),'foreign.pdf','application/pdf',10)$$,'42501','Sale not found','cross-workspace receipt preparation blocked');
select is((select count(*) from api.purchases where id='bbbbbbbb-3309-0000-0000-000000000099'),0::bigint,'cross-workspace sale hidden');
select pg_temp.act_as('aaaaaaaa-0000-0000-0000-000000000006');
select is((select count(*) from api.sale_receipts),0::bigint,'catalog role cannot read financial evidence');
select throws_ok($$select api.sale_command('save',pg_temp.input(),gen_random_uuid())$$,'42501',null,'non-sales role cannot record');
reset role;
select ok(not has_function_privilege('anon','api.sale_command(text,jsonb,uuid)','EXECUTE'),'anonymous cannot run sale commands');
select ok(not has_table_privilege('authenticated','sales.sale_requests','SELECT'),'request ledger is private');
select * from finish();
rollback;
