begin;
create extension if not exists pgtap with schema extensions;
select no_plan();
create function pg_temp.act_as(uid text) returns void language sql as $$ select set_config('request.jwt.claims',json_build_object('sub',uid,'role','authenticated')::text,true); $$;
insert into identity.accounts(id,workspace_id,name) values('aaaaaaaa-3412-0000-0000-000000000001','11111111-1111-1111-1111-111111111111','Synthetic company without opportunities');
insert into identity.contacts(id,workspace_id,display_name) values('bbbbbbbb-3412-0000-0000-000000000001','11111111-1111-1111-1111-111111111111','Synthetic opportunity contact');
create temp table results(id uuid); grant all on results to authenticated;
create temp table metrics(pipeline bigint,quotes bigint,scorecard numeric,open_count integer); grant all on metrics to authenticated;
create function pg_temp.reject_opportunity_history() returns trigger language plpgsql as $$ begin if new.body='Synthetic forced history failure' then raise exception 'Synthetic forced history failure'; end if; return new; end $$;
create trigger reject_opportunity_history before insert on sales.activities for each row execute function pg_temp.reject_opportunity_history();
create function pg_temp.input(extra jsonb default '{}') returns jsonb language sql as $$ select jsonb_build_object('account_id','aaaaaaaa-3412-0000-0000-000000000001','name','Synthetic opportunity','next_action','Send options','next_action_due_at','2026-10-01T10:00:00+08:00','currency','MYR','estimated_value',1000)||extra; $$;
create function pg_temp.cmd(action text,extra jsonb default '{}') returns jsonb language sql as $$ select api.opportunity_command(action,pg_temp.input(jsonb_build_object('id',o.id,'version',o.version)||extra),gen_random_uuid()) from api.opportunities o join results r on r.id=o.id; $$;
set local role authenticated;
select pg_temp.act_as('aaaaaaaa-0000-0000-0000-000000000003');
insert into results select (api.opportunity_command('create',pg_temp.input(),'dddddddd-3412-0000-0000-000000000001')->>'opportunity_id')::uuid;
select is((select project_id from api.opportunities o join results using(id)),null::uuid,'company opportunity does not force a physical project');
select is((select owner_id from api.opportunities o join results using(id)),'aaaaaaaa-0000-0000-0000-000000000003'::uuid,'salesperson owns new opportunity');
select is((api.opportunity_command('create',pg_temp.input(),'dddddddd-3412-0000-0000-000000000001')->>'opportunity_id')::uuid,(select id from results),'creation retry is idempotent');
select throws_ok($$select api.opportunity_command('create',pg_temp.input('{"name":"Different retry"}'),'dddddddd-3412-0000-0000-000000000001')$$,'23514','Retry differs from original command','changed retry rejected');
select throws_ok($$select api.opportunity_command('create',pg_temp.input('{"account_id":null}'),gen_random_uuid())$$,'23514','Choose a contact or company','orphan opportunity rejected');
select throws_ok($$select api.opportunity_command('create',pg_temp.input('{"owner_id":"aaaaaaaa-0000-0000-0000-000000000004"}'),gen_random_uuid())$$,'42501','permission denied: sales.assign','rep cannot assign another owner');
select throws_ok($$select api.opportunity_command('create',pg_temp.input('{"account_id":"aaaaaaaa-3412-0000-0000-000000000099"}'),gen_random_uuid())$$,'23514','Choose an active company in this workspace','foreign or missing company rejected');
select throws_ok($$select api.opportunity_command('create',pg_temp.input('{"contact_id":"bbbbbbbb-3412-0000-0000-000000000099"}'),gen_random_uuid())$$,'23514','Choose an active contact in this workspace','foreign or missing contact rejected');
select throws_ok($$select pg_temp.cmd('edit','{"next_action":""}')$$,'23514','Enter a next action and due date','open opportunity needs next action');
select lives_ok($$select pg_temp.cmd('edit','{"name":"Updated opportunity","notes":"Tile sample remark"}')$$,'owner can edit');
select is((select notes from api.opportunities o join results using(id)),'Tile sample remark','edited remark persists');
select throws_ok($$select pg_temp.cmd('edit','{"version":1}')$$,'40001','Opportunity changed. Refresh and try again.','stale edit cannot overwrite');
select throws_ok($$update api.opportunities set name='Bypass' where id=(select id from results)$$,'42501',null,'direct mutation denied');
select throws_ok($$select pg_temp.cmd('archive')$$,'23514','A reason is required','archive requires reason');
select lives_ok($$select api.opportunity_photo_command('prepare',(select id from results),'eeeeeeee-3412-0000-0000-000000000001','{"file_name":"sample.png","content_type":"image/png","file_size":100,"remark":"Synthetic tile sample"}')$$,'prepare private opportunity photo');
select throws_ok($$select api.opportunity_photo_command('finish',(select id from results),'eeeeeeee-3412-0000-0000-000000000001')$$,'23514','Upload the photo before saving','metadata alone is not a completed photo');
select throws_ok($$select api.opportunity_photo_command('prepare',(select id from results),gen_random_uuid(),'{"file_name":"bad.svg","content_type":"image/svg+xml","file_size":100,"remark":"Bad type"}')$$,'23514','Choose a JPG, PNG or WebP up to 5 MB and enter a remark','active upload types rejected');
select throws_ok($$select api.opportunity_photo_command('prepare',(select id from results),gen_random_uuid(),'{"file_name":"huge.png","content_type":"image/png","file_size":5242881,"remark":"Huge file"}')$$,'23514','Choose a JPG, PNG or WebP up to 5 MB and enter a remark','oversize image rejected');
select pg_temp.act_as('aaaaaaaa-0000-0000-0000-000000000004');
select is((select count(*) from api.opportunity_photos where id='eeeeeeee-3412-0000-0000-000000000001'),1::bigint,'shared salesperson can read private workspace photo metadata');
select lives_ok($$select pg_temp.cmd('archive','{"reason":"Shared teammate archive"}')$$,'shared salesperson can archive a teammate opportunity');
select ok((select archived_at is not null from api.opportunities o join results using(id)),'teammate archive persists');
select lives_ok($$select pg_temp.cmd('restore','{"reason":"Continue synthetic workflow"}')$$,'shared salesperson can restore the teammate opportunity');
select throws_ok($$select api.opportunity_photo_command('finish',(select id from results),'eeeeeeee-3412-0000-0000-000000000001')$$,'42501','Only the uploader can finish this upload','shared editor cannot finalize another staff member''s upload');
select pg_temp.act_as('aaaaaaaa-0000-0000-0000-000000000003');
select lives_ok($$insert into storage.objects(bucket_id,name,metadata) select 'opportunity-photos',object_path,'{"size":100,"mimetype":"image/png"}' from api.opportunity_photos where id='eeeeeeee-3412-0000-0000-000000000001'$$,'authenticated uploader can insert at the reserved photo path');
select lives_ok($$select api.opportunity_photo_command('finish',(select id from results),'eeeeeeee-3412-0000-0000-000000000001')$$,'actual upload can be finalized');
select lives_ok($$select api.opportunity_photo_command('finish',(select id from results),'eeeeeeee-3412-0000-0000-000000000001')$$,'upload finalize is idempotent');
select pg_temp.act_as('aaaaaaaa-0000-0000-0000-000000000002');
insert into api.quotes(workspace_id,opportunity_id,quote_number,status) values('11111111-1111-1111-1111-111111111111',(select id from results),'SYNTHETIC-ARCHIVE-QUOTE','issued');
insert into metrics select (select sum(opportunities) from api.report_pipeline()),(select sum(quotes) from api.report_quotes()),(api.sales_scorecard()->>'pipeline')::numeric,(api.command_centre_summary()->>'open_opportunities')::integer;
select pg_temp.act_as('aaaaaaaa-0000-0000-0000-000000000003');
select lives_ok($$select pg_temp.cmd('archive','{"reason":"Duplicate pursuit"}')$$,'archive is reversible');
select ok((select archived_at is not null from api.opportunities o join results using(id)),'archived marker persists');
select pg_temp.act_as('aaaaaaaa-0000-0000-0000-000000000002');
select is((select sum(opportunities)::bigint from api.report_pipeline()),(select pipeline-1 from metrics),'pipeline report excludes archived pursuit');
select is((select sum(quotes)::bigint from api.report_quotes()),(select quotes-1 from metrics),'quote report excludes archived pursuit');
select is((api.sales_scorecard()->>'pipeline')::numeric,(select scorecard-1000 from metrics),'sales scorecard excludes archived estimate');
select is((api.command_centre_summary()->>'open_opportunities')::integer,(select open_count-1 from metrics),'command centre excludes archived pursuit');
select pg_temp.act_as('aaaaaaaa-0000-0000-0000-000000000003');
select is((select count(*) from api.opportunity_photos where id='eeeeeeee-3412-0000-0000-000000000001'),1::bigint,'archive preserves photo evidence');
select throws_ok($$select pg_temp.cmd('edit')$$,'23514','Restore the opportunity before changing it','archived opportunity cannot edit');
select throws_ok($$select api.change_opportunity_stage((select id from results),'qualified','Synthetic reason','Follow up',now()+interval '1 day')$$,'23514','Restore the opportunity before changing it','old stage RPC cannot modify archived opportunity');
select lives_ok($$select pg_temp.cmd('restore','{"reason":"Original pursuit still active"}')$$,'restore succeeds');
select ok((select archived_at is null from api.opportunities o join results using(id)),'restored opportunity resumes in its original stage');
select lives_ok($$select api.opportunity_photo_command('remove',(select id from results),'eeeeeeee-3412-0000-0000-000000000001','{"reason":"Wrong sample"}')$$,'photo can be removed with reason');
select is((select count(*) from storage.objects where bucket_id='opportunity-photos'),0::bigint,'removed photo no longer grants storage read');
select pg_temp.act_as('aaaaaaaa-0000-0000-0000-000000000002');
select lives_ok($$select pg_temp.cmd('reassign','{"owner_id":"aaaaaaaa-0000-0000-0000-000000000004"}')$$,'manager can reassign');
select lives_ok($$select api.opportunity_command('create',pg_temp.input('{"contact_id":"bbbbbbbb-3412-0000-0000-000000000001","account_id":null,"create_project":true,"project_name":"Synthetic new project"}'),gen_random_uuid())$$,'contact and new project can be created atomically with opportunity');
select throws_ok($$select api.opportunity_command('create',pg_temp.input('{"create_project":true,"project_name":"Synthetic rolled back project","notes":"Synthetic forced history failure"}'),gen_random_uuid())$$,'P0001','Synthetic forced history failure','history failure aborts multi-record creation');
reset role;
select is((select count(*) from identity.projects where name='Synthetic new project'),1::bigint,'one physical project created');
select is((select count(*) from identity.projects where name='Synthetic rolled back project'),0::bigint,'failed creation leaves no orphan project');
select is((select count(*) from sales.purchases where opportunity_id=(select id from results)),0::bigint,'opportunity work never invents recorded revenue');
select * from finish();
rollback;
