begin;
create extension if not exists pgtap with schema extensions;
select no_plan();
create function pg_temp.act_as(uid text) returns void language sql as $$ select set_config('request.jwt.claims',json_build_object('sub',uid,'role','authenticated')::text,true); $$;
create temp table target(id uuid); grant all on target to authenticated;
create temp table saved(key text,id uuid); grant all on saved to authenticated;
create function pg_temp.draft(extra jsonb default '{}') returns jsonb language sql as $$ select jsonb_build_object('title','Synthetic creative contract','template','graphic','format','graphic','source_mode','no_filming','owner_id','aaaaaaaa-0000-0000-0000-000000000003','reviewer_id','aaaaaaaa-0000-0000-0000-000000000007','production_due','2030-09-01','review_due','2030-09-02','channels',jsonb_build_array('instagram','tiktok'),'brief',jsonb_build_object('objective','Explain tile care','audience','Homeowners','key_message','Use appropriate cleaning','cta','Learn more'))||extra; $$;
create function pg_temp.cmd(action text,data jsonb default '{}',request uuid default gen_random_uuid()) returns jsonb language sql as $$ select api.creative_command(action,t.id,c.revision,request,data) from target t join api.creative_items c on c.id=t.id; $$;
create function pg_temp.latest() returns uuid language sql as $$ select id from api.creative_versions where creative_id=(select id from target) order by version_no desc limit 1; $$;
create function pg_temp.review(decision text default 'approved') returns jsonb language sql as $$ select pg_temp.cmd('review',jsonb_build_object('version_id',pg_temp.latest(),'decision',decision,'notes','Synthetic reviewed specific export and actual uses','restrictions_confirmed',true)); $$;
create function pg_temp.submit() returns jsonb language sql as $$ select pg_temp.cmd('submit','{"export_label":"Synthetic specific export","review_url":"https://example.test/v1.mp4","final_url":"https://example.test/final1.mp4","access_confirmed":true,"specific_export_confirmed":true}'); $$;
-- Two customer sources, independent permissions, one shared booking.
insert into marketing.content_opportunities(id,workspace_id,project_id,status) select '11111111-0016-0000-0000-000000000001',workspace_id,id,'accepted' from identity.projects where workspace_id='11111111-1111-1111-1111-111111111111' limit 1;
insert into marketing.content_opportunities(id,workspace_id,project_id,status) select '11111111-0016-0000-0000-000000000002',workspace_id,id,'accepted' from identity.projects where workspace_id='11111111-1111-1111-1111-111111111111' limit 1;
insert into marketing.media_permission_records(workspace_id,content_opportunity_id,status,permitted_uses) values ('11111111-1111-1111-1111-111111111111','11111111-0016-0000-0000-000000000001','approved',array['social']),('11111111-1111-1111-1111-111111111111','11111111-0016-0000-0000-000000000002','revoked',array['social']);
insert into marketing.shoot_bookings(id,workspace_id,content_opportunity_id,status,starts_at,ends_at,title) values ('11111111-0016-0000-0000-000000000003','11111111-1111-1111-1111-111111111111','11111111-0016-0000-0000-000000000001','completed','2026-08-01T10:00:00+08','2026-08-01T11:00:00+08','Synthetic completed shoot');
set local role authenticated;
select pg_temp.act_as('aaaaaaaa-0000-0000-0000-000000000003');
insert into target select (api.creative_command('create',null,null,'aaaaaaaa-0016-0000-0000-000000000001',pg_temp.draft())->>'id')::uuid;
select is((api.creative_command('create',null,null,'aaaaaaaa-0016-0000-0000-000000000001',pg_temp.draft())->>'id')::uuid,(select id from target),'create retry returns same creative');
select throws_ok($$select api.creative_command('create',null,null,'aaaaaaaa-0016-0000-0000-000000000001',pg_temp.draft('{"title":"Different"}'))$$,'23514','Request ID was already used for different input','changed retry rejected');
select is((select count(*) from api.creative_sources where creative_id=(select id from target)),0::bigint,'no filming needs no fake customer or shoot');
select throws_ok($$update api.creative_items set phase='approved' where id=(select id from target)$$,'42501',null,'direct phase changes denied');
select lives_ok($$select pg_temp.cmd('phase','{"phase":"preparing"}')$$,'complete draft enters preparing');
select throws_ok($$select pg_temp.cmd('phase','{"phase":"in_production"}')$$,'23514','Confirm source readiness before production','source readiness explicit');
select throws_ok($$select pg_temp.cmd('link_add','{"kind":"reference","label":"Unsafe","url":"javascript:alert(1)","access_state":"confirmed"}')$$,'23514',null,'unsafe links denied in DB');
select throws_ok($$select pg_temp.cmd('link_add','{"kind":"reference","label":"Ephemeral","url":"https://example.test/file?sig=abc","access_state":"confirmed"}')$$,'23514',null,'expiring links denied');
select lives_ok($$select pg_temp.cmd('readiness','{"ready":true,"rights_confirmed":true,"note":"Copy complete; no customer material"}')$$,'no filming readiness works');
select lives_ok($$select pg_temp.cmd('phase','{"phase":"in_production"}')$$,'production begins');
select throws_ok($$select api.creative_command('update',(select id from target),1,gen_random_uuid(),pg_temp.draft())$$,'40001','This creative changed. Refresh before saving.','stale edit denied');
select lives_ok($$select pg_temp.submit()$$,'version1 submitted');
select throws_ok($$select pg_temp.cmd('update',pg_temp.draft())$$,'23514',null,'review brief frozen');
select throws_ok($$select pg_temp.review()$$,'42501','permission denied: creative.approve','writer cannot approve');
select pg_temp.act_as('aaaaaaaa-0000-0000-0000-000000000007');
select lives_ok($$select pg_temp.review('changes_requested')$$,'designated reviewer requests changes');
select is((select phase from api.creative_items where id=(select id from target)),'in_production','changes return production');
select pg_temp.act_as('aaaaaaaa-0000-0000-0000-000000000003');
select lives_ok($$select pg_temp.submit()$$,'version2 submitted');
select is((select count(*) from api.creative_versions where creative_id=(select id from target)),2::bigint,'old versions retained');
select pg_temp.act_as('aaaaaaaa-0000-0000-0000-000000000007');
select lives_ok($$select pg_temp.review()$$,'designated reviewer approves exact latest version');
select is(api.creative_query('detail','{}',(select id from target))->>'stage','approved','zero publication plans never implies published');
select throws_ok($$update api.creative_reviews set notes='changed'$$,'42501',null,'reviews not directly editable');
select lives_ok($$select pg_temp.cmd('publication_plan','{"channel":"instagram","account_label":"Main","intended_use":"organic_social","target_date":"2026-09-01"}')$$,'plan before scheduling');
select lives_ok($$select pg_temp.cmd('publication_plan','{"channel":"tiktok","account_label":"Main","intended_use":"organic_social","target_date":"2026-10-01"}')$$,'second channel separate publication');
insert into saved select channel,id from api.creative_publications where creative_id=(select id from target);
select is((api.creative_query('calendar','{"from":"2026-09-01","to":"2026-10-01"}')->>'total')::integer,1,'September target count differs from October');
select is((api.creative_query('calendar','{"from":"2026-09-01","to":"2026-11-01"}')->>'unique_creatives')::integer,1,'two channel plans count one creative');
select throws_ok($$select pg_temp.cmd('publication_schedule',jsonb_build_object('publication_id',(select id from saved where key='instagram'),'version_id',pg_temp.latest(),'scheduled_at','2030-09-01T10:00:00+08','restrictions_confirmed',true))$$,'23514',null,'date alone is not scheduling evidence');
select lives_ok($$select pg_temp.cmd('publication_schedule',jsonb_build_object('publication_id',(select id from saved where key='instagram'),'version_id',pg_temp.latest(),'scheduled_at','2030-09-01T10:00:00+08','scheduling_method','Synthetic external scheduler confirmation','restrictions_confirmed',true))$$,'schedule exact approved version');
select is(api.creative_query('detail','{}',(select id from target))->>'stage','approved','partial scheduling stays approved');
select lives_ok($$select pg_temp.cmd('publication_schedule',jsonb_build_object('publication_id',(select id from saved where key='tiktok'),'version_id',pg_temp.latest(),'scheduled_at','2030-10-01T10:00:00+08','scheduling_method','Synthetic external scheduler confirmation','restrictions_confirmed',true))$$,'second release scheduled');
select is(api.creative_query('detail','{}',(select id from target))->>'stage','scheduled','all remaining releases scheduled');
select lives_ok($$select pg_temp.cmd('publication_publish',jsonb_build_object('publication_id',(select id from saved where key='instagram'),'version_id',pg_temp.latest(),'published_at','2026-09-01T00:30:00+08','live_url','https://example.test/live1','restrictions_confirmed',true))$$,'late actual confirmation uses actual timestamp');
select is(api.creative_query('detail','{}',(select id from target))->>'stage','scheduled','one published still has remaining scheduled');
select is((api.creative_query('calendar','{"basis":"published","from":"2026-09-01","to":"2026-09-02"}')->>'total')::integer,1,'KL date boundary includes prior UTC day');
select throws_ok($$select pg_temp.cmd('reopen','{"reason":"New cut","external_cancellation_acknowledged":false}')$$,'42501',null,'cannot reopen without external cancellation acknowledgement');
select lives_ok($$select pg_temp.cmd('reopen','{"reason":"Synthetic new cut","external_cancellation_acknowledged":true}')$$,'reopen cancels pending version linkage');
select is((select version_id from api.creative_publications where id=(select id from saved where key='tiktok')),null::uuid,'pending plan loses obsolete approved version');
select is((select status from api.creative_publications where id=(select id from saved where key='instagram')),'published','published history retained');
select is((select approved_version_id from api.creative_items where id=(select id from target)),null::uuid,'new production never inherits approval');
-- Customer compilation checks every source, even no-filming reuse.
select lives_ok($$select pg_temp.cmd('source_add','{"content_opportunity_id":"11111111-0016-0000-0000-000000000001"}')$$,'first customer source linked');
select lives_ok($$select pg_temp.cmd('source_add','{"content_opportunity_id":"11111111-0016-0000-0000-000000000002"}')$$,'second customer source linked');
select throws_ok($$select pg_temp.cmd('source_add','{"content_opportunity_id":"11111111-0016-0000-0000-000000000099"}')$$,'23514',null,'foreign or unknown source rejected');
select lives_ok($$select pg_temp.cmd('readiness','{"ready":true,"rights_confirmed":true,"note":"Synthetic reused graphics confirmed"}')$$,'human readiness separate from DB customer-use checks');
select pg_temp.act_as('aaaaaaaa-0000-0000-0000-000000000003');
select lives_ok($$select pg_temp.submit()$$,'compilation submits');
select pg_temp.act_as('aaaaaaaa-0000-0000-0000-000000000007');
select throws_ok($$select pg_temp.review()$$,'42501',null,'one revoked customer blocks full compilation approval');
reset role;
update marketing.media_permission_records set status='approved',revoked_at=null where content_opportunity_id='11111111-0016-0000-0000-000000000002';
set local role authenticated;
select lives_ok($$select pg_temp.review()$$,'all customer permissions accepted');
select lives_ok($$select pg_temp.cmd('publication_plan','{"channel":"instagram","account_label":"Paid","intended_use":"paid_ads","target_date":"2030-09-01"}')$$,'paid plan may remain draft pending rights');
insert into saved select 'paid',id from api.creative_publications where creative_id=(select id from target) and account_label='Paid';
select throws_ok($$select pg_temp.cmd('publication_schedule',jsonb_build_object('publication_id',(select id from saved where key='paid'),'version_id',pg_temp.latest(),'scheduled_at','2030-09-01T10:00:00+08','scheduling_method','Synthetic scheduler','restrictions_confirmed',true))$$,'42501',null,'organic customer use does not authorize advertising');
select lives_ok($$select pg_temp.cmd('publication_schedule',jsonb_build_object('publication_id',(select id from saved where key='tiktok'),'version_id',pg_temp.latest(),'scheduled_at','2030-09-01T10:00:00+08','scheduling_method','Synthetic scheduler','restrictions_confirmed',true))$$,'organic source can schedule covered channel');
reset role;
update marketing.media_permission_records set expires_at='2029-01-01' where content_opportunity_id='11111111-0016-0000-0000-000000000002';
set local role authenticated;
select throws_ok($$select pg_temp.cmd('publication_schedule',jsonb_build_object('publication_id',(select id from saved where key='tiktok'),'version_id',pg_temp.latest(),'scheduled_at','2030-09-01T10:00:00+08','scheduling_method','Synthetic scheduler','restrictions_confirmed',true))$$,'42501',null,'expiry evaluated at scheduled use date');
select ok((select (j->>'external_action_required')::boolean from jsonb_array_elements(api.creative_query('detail','{}',(select id from target))->'publications') j where j->>'id'=(select id::text from saved where key='tiktok')),'permission change flags external action');
reset role;
update marketing.media_permission_records set status='revoked',revoked_at=now() where content_opportunity_id='11111111-0016-0000-0000-000000000002';
set local role authenticated;
select throws_ok($$select pg_temp.cmd('publication_publish',jsonb_build_object('publication_id',(select id from saved where key='tiktok'),'version_id',pg_temp.latest(),'published_at','2026-09-01T10:00:00+08','live_url','https://example.test/live2','restrictions_confirmed',true))$$,'42501',null,'revoked permission blocks actual release');
-- Server pagination and isolation beyond the first 500.
select lives_ok($$select api.upsert_shoot_booking(p_content_opportunity_id=>'11111111-0016-0000-0000-000000000001',p_starts_at=>'2031-01-01T10:00:00+08',p_ends_at=>'2031-01-01T11:00:00+08',p_status=>'confirmed',p_title=>'Synthetic creative handoff',p_participants=>'[{"user_id":"aaaaaaaa-0000-0000-0000-000000000003","role":"crew"}]')$$,'existing confirmed booking works after interval arithmetic fix');
select is((select count(*) from api.shoot_conflicts('2031-01-01T11:10:00+08','2031-01-01T12:00:00+08',array['aaaaaaaa-0000-0000-0000-000000000003'::uuid]) where kind='travel_buffer' and detail like 'Only 10 minutes%'),1::bigint,'travel buffer warning computes numeric minutes');
select pg_temp.act_as('aaaaaaaa-0000-0000-0000-000000000003');
delete from target;
insert into target select (api.creative_command('create',null,null,gen_random_uuid(),pg_temp.draft('{"title":"Synthetic footage production","source_mode":"new_footage","shoot_booking_id":"11111111-0016-0000-0000-000000000003","brief":{"objective":"Show install","audience":"Homeowner","key_message":"Installation detail","shot_plan":"Required install closeups"}}'))->>'id')::uuid;
select is((select count(*) from api.creative_sources where creative_id=(select id from target)),1::bigint,'create from shoot preserves single source relationship');
select throws_ok($$select pg_temp.cmd('readiness','{"ready":true,"rights_confirmed":true,"note":"Shoot completed"}')$$,'23514','Confirm an accessible raw footage link or a usable shoot output','completed shoot alone is not footage readiness');
select lives_ok($$select pg_temp.cmd('link_add','{"kind":"raw_footage","label":"Synthetic captured coverage","url":"https://example.test/raw-folder","access_state":"confirmed"}')$$,'raw folder linked without fetching');
select lives_ok($$select pg_temp.cmd('readiness','{"ready":true,"rights_confirmed":true,"note":"All mandatory closeups present"}')$$,'shot plan and captured source permit readiness');
reset role;
update marketing.shoot_bookings set starts_at=starts_at+interval '1 day',ends_at=ends_at+interval '1 day' where id='11111111-0016-0000-0000-000000000003';
set local role authenticated;
select is((select source_ready from api.creative_items where id=(select id from target)),false,'rescheduled source invalidates readiness');
select ok((api.creative_query('detail','{}',(select id from target))->'risks') ? 'Linked shoot changed; review source readiness and release dates','source schedule warning visible');
select lives_ok($$select pg_temp.cmd('update',pg_temp.draft('{"source_mode":"existing_footage"}'))$$,'existing footage branch keeps source references');
select lives_ok($$select pg_temp.cmd('readiness','{"ready":true,"rights_confirmed":true,"note":"Existing accessible footage is complete"}')$$,'existing source needs no new shoot');
-- The coordinator has approval, but self approval is deliberately separate.
select pg_temp.act_as('aaaaaaaa-0000-0000-0000-000000000007');
delete from target;
insert into target select (api.creative_command('create',null,null,gen_random_uuid(),pg_temp.draft('{"title":"Synthetic self approval","owner_id":"aaaaaaaa-0000-0000-0000-000000000007"}'))->>'id')::uuid;
select pg_temp.cmd('readiness','{"ready":true,"rights_confirmed":true,"note":"Synthetic copy ready"}');
select pg_temp.cmd('phase','{"phase":"in_production"}');
select pg_temp.submit();
select throws_ok($$select pg_temp.review()$$,'42501','Self approval requires the explicit creative.self_approve grant','coordinator cannot approve own production');
select pg_temp.act_as('aaaaaaaa-0000-0000-0000-000000000001');
select throws_ok($$select pg_temp.review()$$,'42501','Only the designated reviewer can review active submitted work','admin does not silently override designated reviewer');
select pg_temp.cmd('reopen','{"reason":"Synthetic assign explicit approver","external_cancellation_acknowledged":false}');
select pg_temp.cmd('update',pg_temp.draft('{"owner_id":"aaaaaaaa-0000-0000-0000-000000000001","reviewer_id":"aaaaaaaa-0000-0000-0000-000000000001"}'));
select pg_temp.cmd('readiness','{"ready":true,"rights_confirmed":true,"note":"Synthetic copy ready"}');
select pg_temp.submit();
select lives_ok($$select pg_temp.review()$$,'explicit administrator self-approval grant works');
create temp table retry_command as select id,revision,gen_random_uuid() as request from api.creative_items where id=(select id from target);
select lives_ok($$select api.creative_command('publication_plan',id,revision,request,'{"channel":"instagram","account_label":"Synthetic idempotent","intended_use":"organic_social"}') from retry_command$$,'create release plan');
select lives_ok($$select api.creative_command('publication_plan',id,revision,request,'{"channel":"instagram","account_label":"Synthetic idempotent","intended_use":"organic_social"}') from retry_command$$,'same publication retry succeeds despite stale revision');
select is((select count(*) from api.creative_publications where creative_id=(select id from target)),1::bigint,'publication retry never duplicates plan');
select pg_temp.cmd('publication_cancel',jsonb_build_object('publication_id',(select id from api.creative_publications where creative_id=(select id from target)),'reason','Synthetic plan cancelled','external_cancellation_acknowledged',false));
select is(api.creative_query('detail','{}',(select id from target))->>'stage','approved','all cancelled plans never imply published');
select pg_temp.cmd('publication_plan','{"channel":"instagram","account_label":"Synthetic actual","intended_use":"organic_social"}');
select lives_ok($$select pg_temp.cmd('publication_publish',jsonb_build_object('publication_id',(select id from api.creative_publications where creative_id=(select id from target) and status='planned'),'version_id',pg_temp.latest(),'published_at','2026-09-01T10:00:00+08','live_url','https://example.test/actual','restrictions_confirmed',true))$$,'publish now can record approved actual release without scheduling');
select is(api.creative_query('detail','{}',(select id from target))->>'stage','published','all active plans published yields published');
select pg_temp.cmd('reopen','{"reason":"Synthetic revised published cut","external_cancellation_acknowledged":false}');
select pg_temp.submit();
select pg_temp.review();
select is(api.creative_query('detail','{}',(select id from target))->>'stage','approved','newly approved version never inherits an older version publication');
select ok(exists(select 1 from jsonb_array_elements(api.creative_query('list','{"unscheduled":true}') -> 'items') j where j->>'id'=(select id::text from target)),'new version with older publication history is discoverable as unscheduled');
select is((select count(*) from api.creative_publications where creative_id=(select id from target) and status='published'),1::bigint,'older version publication evidence remains intact');
select pg_temp.act_as('aaaaaaaa-0000-0000-0000-000000000003');
select throws_ok($$select pg_temp.cmd('publication_publish','{"publication_id":"11111111-0016-0000-0000-000000000099"}')$$,'42501','permission denied: creative.publish','writer cannot publish');
reset role;
insert into marketing.creative_items(workspace_id,title,template,source_mode,created_by) select '11111111-1111-1111-1111-111111111111','Synthetic bulk creative '||lpad(i::text,4,'0'),'graphic','no_filming','aaaaaaaa-0000-0000-0000-000000000003' from generate_series(1,605) i;
insert into marketing.creative_items(workspace_id,title,template,source_mode,created_by) select id,'Synthetic foreign sentinel','graphic','no_filming','aaaaaaaa-0000-0000-0000-000000000003' from core.workspaces where slug='demo';
set local role authenticated;
select is((api.creative_query('list','{"search":"Synthetic bulk","page_size":100}')->>'total')::integer,605,'total is not capped at 500 or page size');
select is(jsonb_array_length(api.creative_query('list','{"search":"Synthetic bulk","page":7,"page_size":100}')->'items'),5,'last page is accessible');
select is((api.creative_query('list','{"search":"Synthetic bulk creative 0605"}')->>'total')::integer,1,'search finds beyond first500');
select is((api.creative_query('list','{"search":"Synthetic foreign sentinel"}')->>'total')::integer,0,'foreign workspace excluded by definer query');
select is((select count(*) from api.creative_items where title='Synthetic foreign sentinel'),0::bigint,'foreign workspace excluded by view RLS');
select is((api.creative_query('list','{"search":"Synthetic bulk","stage":"approved"}')->'stage_counts'->>'briefing')::integer,605,'stage totals ignore chosen stage but preserve other filters');
select is((api.creative_query('list','{"search":"Synthetic bulk","unscheduled":true}')->>'total')::integer,605,'undated work remains discoverable');
select throws_ok($$select api.creative_query('calendar','{"from":"2026-01-01","to":"2030-01-01"}')$$,'23514',null,'calendar bounded by date range');
reset role;
select throws_ok($$update marketing.creative_versions set notes='mutable' where creative_id=(select id from target)$$,'23514','Creative versions, reviews and events are append-only','immutable submissions even for privileged SQL');
select throws_ok($$delete from marketing.creative_reviews where id=(select id from marketing.creative_reviews limit 1)$$,'23514','Creative versions, reviews and events are append-only','review deletion forbidden');
-- The existing weekly demo workspace reset remains possible; ordinary deletes remain forbidden.
insert into marketing.creative_versions(workspace_id,creative_id,version_no,export_label,review_url,final_url,brief_snapshot,source_snapshot,submitted_by)
 select workspace_id,id,1,'Synthetic demo export','https://example.test/demo','https://example.test/demo','{}','[]','aaaaaaaa-0000-0000-0000-000000000003' from marketing.creative_items where title='Synthetic foreign sentinel';
select lives_ok($$select core.reset_demo_workspace()$$,'existing controlled demo workspace reset cascades creative evidence');
select ok(not has_function_privilege('anon','api.creative_command(text,uuid,integer,uuid,jsonb)','execute'),'anonymous cannot mutate creative');
select ok(not has_function_privilege('anon','api.creative_query(text,jsonb,uuid)','execute'),'anonymous cannot query creative');
select * from finish();
rollback;
