begin;
create extension if not exists pgtap with schema extensions;
select no_plan();
create temp table initial_demo as select id from core.workspaces where slug='demo';
create temp table fixture_ids as select md5(id::text||':creative-demo-v1:'||key)::uuid id from initial_demo,unnest(array['briefing','preparing','production','review','approved','scheduled','published','blocked']) key;
select lives_ok($$select core.build_demo_creative_dataset((select id from initial_demo))$$,'demo fixtures can be built explicitly');
select is((select count(*) from marketing.creative_items c join fixture_ids f using(id)),8::bigint,'eight deterministic synthetic deliverables created');
select lives_ok($$select core.build_demo_creative_dataset((select id from initial_demo))$$,'repeat fixture build is safe');
select is((select count(*) from marketing.creative_items c join fixture_ids f using(id)),8::bigint,'repeat build does not duplicate deliverables');
select is((select count(distinct marketing.creative_stage(c.id,c.phase)) from marketing.creative_items c join fixture_ids f using(id)),7::bigint,'demo covers all seven derived board stages');
select ok(not exists(select 1 from marketing.creative_items c join fixture_ids f using(id) where c.title not like 'Demo:%'),'every demo deliverable is explicitly labeled');
select is((select count(*) from marketing.creative_items c join fixture_ids f using(id) where c.condition='blocked'),1::bigint,'blocked work retains its production phase');
select ok(not exists(select 1 from marketing.creative_items c join fixture_ids f using(id) where c.owner_id is null or c.reviewer_id is null),'guest owns and reviews demo work');
select ok(not exists(select 1 from marketing.creative_publications p join fixture_ids f on f.id=p.creative_id where p.status in ('scheduled','published') and (p.version_id is null or cardinality(marketing.creative_rights_issues(p.creative_id,p.intended_use,coalesce((p.scheduled_at at time zone 'Asia/Kuala_Lumpur')::date,(p.published_at at time zone 'Asia/Kuala_Lumpur')::date)))>0)),'scheduled and published fixtures reference approved versions and covered customer use');
select is((select count(*) from marketing.creative_sources s join fixture_ids f on f.id=s.creative_id),7::bigint,'general graphic needs no fabricated customer source');
select ok(exists(select 1 from marketing.creative_items c join fixture_ids f using(id) where c.condition='blocked' and cardinality(marketing.creative_rights_issues(c.id))>0),'blocked fixture exposes customer media permission issue');
select throws_ok($$select core.build_demo_creative_dataset('11111111-1111-1111-1111-111111111111')$$,'42501','Creative demo fixtures require the isolated demo workspace','real workspace is rejected');
select is((select count(*) from marketing.creative_items where workspace_id='11111111-1111-1111-1111-111111111111' and title like 'Demo:%'),0::bigint,'no demo data inserted into ordinary workspace');
select ok(not has_function_privilege('authenticated','core.build_demo_creative_dataset(uuid)','execute'),'ordinary callers cannot seed fixtures');
select ok(not has_function_privilege('authenticated','core.build_demo_dataset_before_creative(uuid)','execute'),'ordinary callers cannot bypass wrapper');
select throws_ok($$delete from marketing.content_opportunities where id=(select s.content_opportunity_id from marketing.creative_sources s join fixture_ids f on f.id=s.creative_id limit 1); set constraints all immediate$$,'23503',null,'deferred checks still prevent deleting a live linked source');
-- Transaction rollback restores the shared demo; no actual runtime reset survives this test.
select lives_ok($$select core.reset_demo_workspace()$$,'existing weekly reset builds creative fixtures through same path');
select isnt((select id from initial_demo),core.demo_workspace_id(),'controlled reset recreates demo identity');
select is((select count(*) from marketing.creative_items where workspace_id=core.demo_workspace_id() and title like 'Demo:%'),8::bigint,'reset reproduces eight demo cards');
select is((select count(distinct marketing.creative_stage(id,phase)) from marketing.creative_items where workspace_id=core.demo_workspace_id()),7::bigint,'reset preserves derived-stage examples');
select lives_ok($$set constraints all immediate$$,'all deferred evidence constraints hold after demo reset');
select * from finish();
rollback;
