"use client";
import Link from "next/link";
import { useRouter } from "next/navigation";
import type { ColumnDef } from "@tanstack/react-table";
import { PageBody, PageHeader } from "@/components/patterns/page-header";
import { MetricCard } from "@/components/patterns/metric-card";
import { DataTable, MoneyCell } from "@/components/patterns/data-table";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Card } from "@/components/ui/card";
import { formatDateTime } from "@/lib/format";
import { PLATFORM_LABELS, rate, reportingToday, type FunnelData, type FunnelHistory, type ReportPeriod } from "@/features/reports/funnel-schema";

const money = (n: number) => new Intl.NumberFormat("en-MY", { style: "currency", currency: "MYR", maximumFractionDigits: 2 }).format(n);
const selector = "h-9 rounded-md border bg-background px-2 text-sm";
type Channel = FunnelData["channels"][number]; type Staff = FunnelData["staff"][number]; type HistoryRow = FunnelHistory["rows"][number];

export function FunnelDashboard({ data, history, period, locations, canSpend }: { data: FunnelData; history: FunnelHistory | null; period: ReportPeriod; locations: { id: string; name: string }[]; canSpend: boolean }) {
  const router = useRouter(); const s = data.summary;
  function href(changes: Partial<ReportPeriod> = {}, anchor = "history") {
    const params = new URLSearchParams();
    for (const [k, v] of Object.entries({ ...period, page: 1, ...changes })) if (v) params.set(k, String(v));
    return `/insights/reports/funnel?${params}#${anchor}`;
  }
  const channelColumns: ColumnDef<Channel, unknown>[] = [
    { accessorKey: "platform", header: "Recorded origin", cell: ({ row }) => <span className="font-medium">{PLATFORM_LABELS[row.original.platform]}</span> },
    { accessorKey: "spend", header: "Period spend", meta: { hint: "Costs including tax, less vendor credits, incurred during the selected period. Shared costs are not allocated to a channel." }, cell: ({ row: { original: r } }) => ["walk_in", "other_unknown"].includes(r.platform) ? "—" : <div><MoneyCell value={r.spend} /><p className="text-xs text-muted-foreground">{r.covered_days}/{r.expected_days} days checked</p></div> },
    { accessorKey: "leads", header: "New inquiries", cell: ({ row: { original: r } }) => r.platform === "shared" ? "—" : history ? <Link className="underline underline-offset-4" href={href({ kind: "leads", channel: r.platform as ReportPeriod["channel"], staff: "", contact: "" })}>{r.leads}</Link> : r.leads },
    { accessorKey: "whatsapp_sent", header: "WA sent", meta: { hint: "Inquiries in this cohort with a manually recorded WhatsApp send before the as-of cutoff." } },
    { accessorKey: "whatsapp_replied", header: "WA replied", meta: { hint: "Customer replies explicitly marked as WhatsApp; staff responses do not count as customer replies." } },
    { accessorKey: "showroom", header: "Visited showroom", meta: { hint: "Inquiries with at least one linked visit by the as-of cutoff. Repeat visits count once here." } },
    { accessorKey: "closed", header: "Closed sale", meta: { hint: "Inquiries with positive documented net sales through the as-of cutoff. A won opportunity is not a documented sale." } },
    { id: "conversion", header: "Lead → sale", cell: ({ row: { original: r } }) => r.platform === "shared" ? "—" : rate(r.closed, r.leads) },
    { id: "reply_sale", header: "Reply → sale", meta: { hint: "Inquiries with both a WhatsApp reply and a documented sale / inquiries with a WhatsApp reply. The same cohort is used on both sides." }, cell: ({ row: { original: r } }) => r.platform === "shared" ? "—" : rate(r.replied_and_closed, r.whatsapp_replied) },
    { id: "cpl", header: "Cost / source lead", meta: { hint: "Period channel ad spend / same-period inquiries with that recorded origin. Paid versus organic origin is not yet verified. N/A until coverage is complete; location-filtered costs are not allocated." }, cell: ({ row: { original: r } }) => !period.location && ["tiktok", "meta", "google_ads"].includes(r.platform) && r.covered_days === r.expected_days && r.leads > 0 && r.spend >= 0 ? money(r.spend / r.leads) : "N/A" },
    { accessorKey: "cohort_revenue", header: "Cohort net sales", meta: { hint: "Positive net sales credited to this inquiry cohort through the as-of date, including later months. This is separate from period revenue in MER." }, cell: ({ row }) => <MoneyCell value={row.original.cohort_revenue} /> },
  ];
  const staffColumns: ColumnDef<Staff, unknown>[] = [
    { accessorKey: "name", header: "Showroom team", cell: ({ row }) => history && row.original.id ? <Link className="font-medium underline underline-offset-4" href={href({ kind: "visits", staff: row.original.id, channel: "", contact: "" })}>{row.original.name}</Link> : row.original.name },
    { accessorKey: "visits", header: "Visits handled" }, { accessorKey: "customers", header: "Identified customers", meta: { hint: "Distinct identified customers per staff member. A customer handled by two staff can appear in both rows." } },
    { accessorKey: "converted_visits", header: "Visits with a sale" },
    { id: "rate", header: "Visit conversion", cell: ({ row }) => rate(row.original.converted_visits, row.original.visits) },
    { accessorKey: "revenue", header: "Linked net sales", cell: ({ row }) => <MoneyCell value={row.original.revenue} />, meta: { hint: "Net sales linked to these visits through the as-of date. Staff is the visit handler, not necessarily the salesperson." } },
    { accessorKey: "activities", header: "Logged visit activity", meta: { hint: "Activities explicitly attached to a visit and recorded by this staff member during the selected period. Work done outside the app is not inferred." } },
  ];
  const historyColumns: ColumnDef<HistoryRow, unknown>[] = [
    { accessorKey: "at_time", header: "When", cell: ({ row }) => formatDateTime(row.original.at_time) },
    { accessorKey: "customer", header: "Customer", cell: ({ row: { original: r } }) => <div>{r.contact_id ? <Link href={`/sales/contacts/${r.contact_id}`} className="font-medium underline underline-offset-4">{r.customer ?? "Customer"}</Link> : r.customer ?? "Unidentified"}{r.contact_id && <p><Link className="text-xs text-info underline" href={href({ kind: "sales", contact: r.contact_id, staff: "", channel: "" })}>Purchases in period</Link></p>}</div> },
    { accessorKey: "label", header: "Record", cell: ({ row: { original: r } }) => <Link className="underline underline-offset-4" href={period.kind === "sales" ? `/sales/record-sale?id=${r.id}` : period.kind === "leads" ? `/sales/inbox?lead=${r.id}` : `/sales/walk-ins?visit=${r.id}`}>{r.label ?? "Open record"}</Link> },
    { accessorKey: "staff", header: period.kind === "visits" ? "Visit handler" : period.kind === "leads" ? "Inquiry owner" : "Salesperson" },
    { accessorKey: "location", header: "Showroom" }, { accessorKey: "source", header: "Recorded origin" },
    { accessorKey: "state", header: "Recorded state" }, { accessorKey: "sale_count", header: "Positive sales" },
    { accessorKey: "net_sales", header: "Linked net sales", cell: ({ row }) => <MoneyCell value={row.original.net_sales} /> },
    { accessorKey: "collections", header: "Linked collections", cell: ({ row }) => <MoneyCell value={row.original.collections} />, meta: { hint: "Reviewed payments minus cash refunds linked to this record, through the as-of date; includes tax and may span multiple months." } },
    { accessorKey: "notes", header: "Remarks", cell: ({ row }) => <span className="block max-w-80 whitespace-normal text-xs">{row.original.notes || "—"}</span> },
  ];
  const periodInfo = { grain: `${period.from} to ${period.to} · Asia/Kuala_Lumpur`, freshness: formatDateTime(data.computed_at) };
  return <PageBody><PageHeader title="Marketing & showroom dashboard" description="Follow spending, inquiry outcomes and the showroom customer journey."><div className="flex flex-wrap gap-2">{canSpend && <Button variant="outline" asChild><Link href={`/marketing/spend?from=${period.from}&to=${period.to}`}>Enter marketing spend</Link></Button>}<Button variant="outline" onClick={() => router.refresh()}>Refresh dashboard</Button></div></PageHeader>
    <form method="get" className="flex flex-wrap items-end gap-3 rounded-xl border bg-card p-4"><label className="grid gap-1 text-xs font-medium">Period from<Input type="date" name="from" defaultValue={period.from} required /></label><label className="grid gap-1 text-xs font-medium">Period to<Input type="date" name="to" defaultValue={period.to} max={reportingToday()} required /></label><label className="grid gap-1 text-xs font-medium">Outcomes through<Input type="date" name="asof" defaultValue={period.asof} max={reportingToday()} required /></label><label className="grid gap-1 text-xs font-medium">Showroom<select name="location" defaultValue={period.location || ""} className={selector}><option value="">All locations</option>{locations.map(l => <option key={l.id} value={l.id}>{l.name}</option>)}</select></label><Button>Apply filters</Button><span className="text-xs text-muted-foreground">Updated {formatDateTime(data.computed_at)}</span></form>
    <div className="space-y-3"><h2 className="text-base font-semibold">Business activity during the period</h2><div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4">
      <MetricCard label="Marketing spend" value={money(s.spend)} hint={s.spend_complete ? "All cost groups checked" : "Partial · spending coverage incomplete"} tone={s.spend_complete ? "neutral" : "warning"} info={{ ...periodInfo, definition: "Incurred advertising and shared marketing invoice costs including tax, less dated credits. All locations.", source: "Marketing cost ledger", caveat: "Missing days do not imply zero spend. Unallocated creative and influencer costs are included in total marketing spend." }} />
      <MetricCard label="Recorded net sales" value={money(s.revenue)} hint="Discounts and revenue credits deducted · tax excluded" info={{ ...periodInfo, definition: "Sum of dated sale confirmation, credit and void revenue events in this period, excluding sales tax.", source: "Reviewed sales and sales events", caveat: `${s.unclassified_sales} historical sales documents remain unclassified and excluded.` }} />
      <MetricCard label="Collections" value={money(s.collections)} hint="Actual payments less cash refunds · includes tax" info={{ ...periodInfo, definition: "Reviewed cash collections minus cash refunds by payment date. Credit terms and unreviewed historical payments are excluded.", source: "Reviewed purchase payments" }} />
      <MetricCard label="MER" value={s.mer === null ? "N/A" : `${s.mer.toFixed(2)}×`} hint={period.location ? "Shared spend is not allocated to showrooms" : !s.spend_complete ? "Confirm spending coverage to calculate" : s.spend <= 0 ? "Marketing spend must be positive" : "Recorded net sales ÷ total marketing invoice cost"} info={{ ...periodInfo, definition: "Business-period recorded revenue excluding sales tax divided by total marketing cost including tax.", source: "Sales events / marketing cost ledger", caveat: "MER includes all recorded business revenue; it does not prove that advertising caused every sale. Revenue coverage is limited to reviewed records." }} />
    </div></div>
    {(s.unclassified_sales > 0 || s.unreviewed_payments > 0 || s.foreign_sales > 0) && <p className="rounded-lg border border-warning/40 bg-warning/10 p-3 text-sm">Financial coverage: {s.unclassified_sales} unclassified historical documents, {s.unreviewed_payments} unreviewed payments, and {s.foreign_sales} non-MYR sales are excluded from their corresponding totals. Review these before treating the dashboard as complete.</p>}
    <Card className="gap-4 p-4"><div><h2 className="font-semibold">Marketing funnel · inquiries created in this period</h2><p className="mt-1 text-xs text-muted-foreground">Progress through {period.asof}. Each inquiry counts once at each milestone; stages may be skipped. Source labels record origin and can include organic inquiries. Website inquiries are not automatically credited to Google Ads.</p></div>
      <div className="grid gap-3 sm:grid-cols-3"><MetricCard compact label="Inquiries in cohort" value={s.leads} info={{ definition: "Nonduplicate inquiries created during the selected period.", grain: "Inquiry creation cohort", source: "Inquiry Inbox" }} /><MetricCard compact label="Inquiries with a sale" value={`${s.closed_leads} · ${rate(s.closed_leads, s.leads)}`} info={{ definition: "Same-cohort inquiries with positive documented net sales through the as-of date, divided by the same cohort's inquiry count.", source: "Inquiries and linked sales events" }} /><MetricCard compact label="Digital-source lead → sale" value={rate(s.closed_online_leads, s.online_leads)} hint={`${s.closed_online_leads} of ${s.online_leads} digital-source inquiries`} info={{ definition: "Documented sales from inquiries recorded as TikTok, Meta, Facebook, Instagram, Google Ads, website, WhatsApp, DM or email, divided by those inquiries in this creation cohort.", source: "Recorded inquiry sources and sales", caveat: "These are recorded entry/origin labels, not verified paid advertising attribution." }} /></div>
      <DataTable columns={channelColumns} data={data.channels} rowKey={r => r.platform} searchable={false} columnToggle={false} hidePagination />
    </Card>
    <Card className="gap-4 p-4"><div><h2 className="font-semibold">Showroom funnel · visits during this period</h2><p className="mt-1 text-xs text-muted-foreground">Sales linked to those visits through {period.asof}. Customer identity and explicit visit links determine conversion; later purchases are not guessed from a matching name.</p></div>
      <div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><MetricCard compact label="Total walk-ins" value={s.visits} hint={`${s.identified_visitors} identified visitors · ${s.unidentified_visits} unidentified visits`} info={{ definition: "Every visit during the selected period, including repeat visits. Identified visitors is a distinct customer count.", source: "Walk-in records", grain: "Visit cohort" }} /><MetricCard compact label="Linked to an inquiry" value={s.linked_visits} info={{ definition: "Visits explicitly linked to an existing inquiry. Pending linkage and direct visits are not counted here.", source: "Visit inquiry linkage" }} /><MetricCard compact label="Visits with a sale" value={s.converted_visits} info={{ definition: "Distinct visits linked to positive documented sales by the as-of date. More than one receipt does not create extra converted visits.", source: "Walk-ins and linked sales" }} /><MetricCard compact label="Visit → sale conversion" value={rate(s.converted_visits, s.visits)} info={{ definition: "Visits with a documented sale / all visits in this same visit cohort.", source: "Walk-ins and linked sales" }} /></div>
      <DataTable columns={staffColumns} data={data.staff} rowKey={r => r.id ?? "unassigned"} searchable={false} columnToggle={false} emptyTitle="No showroom visits in this period" emptyDescription="Recorded visits and staff activity will appear here." />
    </Card>
    <section id="history" className="scroll-mt-4 space-y-3"><div className="flex flex-wrap items-center justify-between gap-3"><h2 className="text-base font-semibold">Customer journey & purchase history</h2>{history && <div className="flex flex-wrap gap-2">{(["visits", "leads", "sales"] as const).map(k => <Button key={k} asChild size="sm" variant={period.kind === k ? "default" : "outline"}><Link href={href({ kind: k, staff: "", contact: "", channel: "" })}>{k === "visits" ? "Walk-ins" : k === "leads" ? "Inquiries" : "Purchases"}</Link></Button>)}</div>}</div>
      {!history ? <p className="text-sm text-muted-foreground">Named customer history is available to management and sales managers. Your role can view the aggregate dashboard.</p> : <>
        <p className="text-xs text-muted-foreground">{period.kind === "visits" ? "Visits by visit date" : period.kind === "leads" ? "Inquiries by creation date" : "Purchases by document date"}; linked net sales and collections through {period.asof}. Open the customer record for their full history.{(period.staff || period.channel || period.contact) && <> A drilldown filter is active. <Link className="underline" href={href({ staff: "", contact: "", channel: "" })}>Clear drilldown filter</Link></>}</p>
        <DataTable columns={historyColumns} data={history.rows} rowKey={r => r.id} searchable={false} columnToggle={false} hidePagination emptyTitle="No matching history" emptyDescription="Try a different period or clear the drilldown filter." />
        <div className="flex items-center justify-between text-xs"><span>{history.total} records · page {period.page} of {Math.max(1, Math.ceil(history.total / 25))}</span><div className="flex gap-2">{period.page > 1 && <Button asChild variant="outline" size="sm"><Link href={href({ page: period.page - 1 })}>Previous</Link></Button>}{period.page * 25 < history.total && <Button asChild variant="outline" size="sm"><Link href={href({ page: period.page + 1 })}>Next</Link></Button>}</div></div>
      </>}
    </section>
  </PageBody>;
}
