"use client";

import { useState } from "react";
import Link from "next/link";
import { ArrowRight, CalendarPlus, CheckCircle2, ExternalLink, FilePenLine, Link2, Plus, ShieldCheck, Undo2 } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { RecordDrawer, DrawerSection } from "@/components/patterns/record-drawer";
import { StatusPill, TonePill } from "@/components/patterns/status-pill";
import { DisabledHint, Gated } from "@/components/patterns/explain";
import { useSession } from "@/components/shell/session-context";
import { formatDate, formatDateTime, titleCase } from "@/lib/format";
import type { CreativeDetail, CreativeOptions } from "../types";
import { CHANNEL_LABELS, CREATIVE_CONDITION_META, CREATIVE_STAGE_META, FORMAT_LABELS, LINK_LABELS, PUBLICATION_META, SOURCE_MODE_META, TEMPLATE_META, creativeRiskLabel, USE_LABELS } from "../presentation";
import { EditCreativeDialog } from "./creative-forms";
import { CreativeActionDialog, type CreativeDialogSelection } from "./creative-action-dialog";

function ExternalLinkButton({ href, children }: { href: string; children: React.ReactNode }) {
  return <a href={href} target="_blank" rel="noopener noreferrer" className="inline-flex min-w-0 items-center gap-1 rounded text-sm text-info outline-none hover:underline focus-visible:ring-2 focus-visible:ring-ring"><span className="min-w-0 break-words">{children}</span><ExternalLink className="size-3 shrink-0" aria-hidden /></a>;
}

export function CreativeDrawer({ detail, options, onClose }: { detail: CreativeDetail; options: CreativeOptions; onClose: () => void }) {
  const [tab, setTab] = useState("overview");
  const [editing, setEditing] = useState(false);
  const [selection, setSelection] = useState<CreativeDialogSelection | null>(null);
  const { can, session } = useSession();
  const editable = !["review", "approved"].includes(detail.phase) && detail.condition !== "cancelled";
  const names = new Map(options.members.map((m) => [m.id, m.name]));
  const latest = detail.versions[0];
  const assignedReviewer = detail.reviewer_id === session.userId;
  const selfSubmission = latest?.submitted_by === session.userId || detail.owner_id === session.userId;
  const reviewReason = !assignedReviewer ? `This review is assigned to ${detail.reviewer_name ?? "another person"}.` : selfSubmission && !can("creative.self_approve") ? "Work you own or submitted needs a different reviewer. Ask an administrator to arrange the review." : null;
  const step = detail.phase === "briefing" ? { action: "prepare" as const, label: "Prepare creative" } : detail.phase === "preparing" ? { action: "produce" as const, label: "Start production" } : detail.phase === "in_production" ? { action: "submit" as const, label: "Submit for review" } : null;
  const briefFields: [string, string][] = [["Objective", detail.brief.objective], ["Audience", detail.brief.audience], ["Hook / key message", detail.brief.key_message], ["Call to action", detail.brief.cta], ["Shot plan / interview questions", detail.brief.shot_plan], ["Must-have coverage", detail.brief.mandatory_coverage], ["Caption / copy", detail.brief.caption], ["Claims and offer dates to verify", detail.brief.claims]];

  return <RecordDrawer open onOpenChange={(open) => !open && onClose()} width="xl" title={detail.title} description={`${TEMPLATE_META[detail.template].label}${detail.format ? ` · ${FORMAT_LABELS[detail.format]}` : ""}`} autoFocusTitle>
    <div className="flex flex-wrap items-center gap-2"><StatusPill map={CREATIVE_STAGE_META} value={detail.stage} size="md" />{detail.condition !== "active" && <StatusPill map={CREATIVE_CONDITION_META} value={detail.condition} size="md" />}{detail.channels.map((channel) => <span key={channel} className="rounded border px-2 py-0.5 text-xs text-muted-foreground">{CHANNEL_LABELS[channel] ?? channel}</span>)}</div>
    <div className="flex flex-wrap gap-2">
      {step && <Gated permission="marketing.write"><Button size="sm" disabled={detail.condition !== "active"} onClick={() => setSelection({ action: step.action })}>{step.label}<ArrowRight className="size-3.5" aria-hidden /></Button></Gated>}
      {detail.phase === "review" && <DisabledHint reason={reviewReason}><Gated permission="creative.approve"><Button size="sm" disabled={Boolean(reviewReason) || detail.condition !== "active"} onClick={() => setSelection({ action: "review" })}><ShieldCheck className="size-3.5" aria-hidden />Review version</Button></Gated></DisabledHint>}
      {editable && <Gated permission="marketing.write"><Button size="sm" variant="outline" onClick={() => setEditing(true)}><FilePenLine className="size-3.5" aria-hidden />Edit brief</Button></Gated>}
      {(["review", "approved"].includes(detail.phase)) && <Gated permission="marketing.write"><Button size="sm" variant="outline" onClick={() => setSelection({ action: "reopen" })}><Undo2 className="size-3.5" aria-hidden />Reopen for changes</Button></Gated>}
      <Gated permission="marketing.write"><Button size="sm" variant="outline" onClick={() => setSelection({ action: "condition" })}>Update work status</Button></Gated>
    </div>
    {detail.condition !== "active" && <div className="rounded-md border border-warning/30 bg-warning/5 p-3 text-sm"><p className="font-medium">{detail.blocker_reason ?? CREATIVE_CONDITION_META[detail.condition].label}</p>{detail.next_action && <p className="mt-1">Next: {detail.next_action}</p>}<p className="mt-1 text-xs text-muted-foreground">{names.get(detail.blocker_owner_id ?? "") ?? "No responsible person"} · Review {formatDate(detail.blocker_review_date)}</p></div>}
    {detail.risks.length > 0 && <div className="rounded-md border border-warning/30 bg-warning/5 p-3"><p className="text-xs font-semibold">Needs attention</p><ul className="mt-1 list-disc space-y-1 pl-4 text-xs text-muted-foreground">{detail.risks.map((risk) => <li key={risk}>{creativeRiskLabel(risk)}</li>)}</ul></div>}
    <Tabs value={tab} onValueChange={setTab} className="min-w-0">
      <div className="max-w-full overflow-x-auto"><TabsList className="w-max"><TabsTrigger value="overview">Overview</TabsTrigger><TabsTrigger value="brief">Brief & shot plan</TabsTrigger><TabsTrigger value="sources">Sources</TabsTrigger><TabsTrigger value="versions">Versions & review</TabsTrigger><TabsTrigger value="publishing">Publishing</TabsTrigger><TabsTrigger value="activity">Activity</TabsTrigger></TabsList></div>
      <TabsContent value="overview" className="space-y-5 pt-3">
        <dl className="grid gap-4 text-sm sm:grid-cols-2">{[["Owner", detail.owner_name ?? "Unassigned"], ["Reviewer", detail.reviewer_name ?? "Unassigned"], ["Production due", formatDate(detail.production_due)], ["Review due", formatDate(detail.review_due)], ["Priority", titleCase(detail.priority)], ["Next target release", detail.next_target_date ? formatDate(detail.next_target_date) : "Unscheduled"]].map(([label, value]) => <div key={label}><dt className="text-xs text-muted-foreground">{label}</dt><dd className="mt-1 font-medium">{value}</dd></div>)}</dl>
        <DrawerSection title="Next action"><p className="text-sm">{detail.next_action || CREATIVE_STAGE_META[detail.stage].hint}</p></DrawerSection>
        <section className="rounded-lg border bg-muted/20 p-4"><div className="flex items-center gap-2 text-sm font-medium"><CheckCircle2 className="size-4" aria-hidden />Source material</div><p className="mt-2 text-sm">{SOURCE_MODE_META[detail.source_mode].label}</p><p className="mt-1 text-xs text-muted-foreground">{SOURCE_MODE_META[detail.source_mode].prompt}</p><div className="mt-3 flex flex-wrap items-center gap-2"><TonePill tone={detail.source_ready ? "success" : "warning"} label={detail.source_ready ? "Readiness confirmed" : "Readiness not confirmed"} /><Button size="sm" variant="outline" onClick={() => setTab("sources")}>Open sources</Button></div></section>
        <section className="rounded-lg border p-4"><h3 className="text-sm font-medium">Channel releases</h3><p className="mt-2 text-sm text-muted-foreground">{detail.publication_count} active plans · {detail.scheduled_count} scheduled · {detail.published_count} published</p><Button size="sm" variant="outline" className="mt-3" onClick={() => setTab("publishing")}>Open publishing</Button></section>
      </TabsContent>
      <TabsContent value="brief" className="space-y-4 pt-3"><p className="rounded-md bg-primary/5 p-3 text-xs">{TEMPLATE_META[detail.template].prompt}</p>{briefFields.map(([label, value]) => <DrawerSection key={label} title={label}><p className="whitespace-pre-wrap break-words text-sm text-muted-foreground">{value || "Not added yet"}</p></DrawerSection>)}</TabsContent>
      <TabsContent value="sources" className="space-y-5 pt-3">
        <div className="flex flex-wrap gap-2"><Gated permission="marketing.write"><Button size="sm" variant="outline" disabled={!editable} onClick={() => setSelection({ action: "source_add" })}><Plus className="size-3.5" aria-hidden />Link opportunity / shoot</Button></Gated><Gated permission="marketing.write"><Button size="sm" variant="outline" disabled={!editable} onClick={() => setSelection({ action: "link_add" })}><Link2 className="size-3.5" aria-hidden />Add link</Button></Gated><Gated permission="marketing.write"><Button size="sm" disabled={!editable} onClick={() => setSelection({ action: "readiness" })}>Confirm readiness</Button></Gated></div>
        {!editable && <p className="text-xs text-muted-foreground">Reopen this creative before changing the sources of submitted or approved content.</p>}
        <DrawerSection title="Linked opportunities and shoots">
          {detail.sources.length === 0 ? <p className="rounded-md border border-dashed p-4 text-sm text-muted-foreground">No customer/project source linked. No-filming work can continue without a shoot; any customer material still needs its original source relationship.</p> : <ul className="space-y-3">{detail.sources.map((source) => <li key={source.id} className="space-y-2 rounded-lg border p-3"><div className="flex items-start justify-between gap-3"><Link className="text-sm font-medium text-info hover:underline" href={`/marketing/content-opportunities?opportunity=${source.content_opportunity_id}`}>{source.title}</Link>{editable && <Gated permission="marketing.write"><Button size="sm" variant="ghost" onClick={() => setSelection({ action: "source_remove", targetId: source.id })}>Remove</Button></Gated>}</div>{source.shoot_booking_id ? <Link href={`/marketing/shoot-calendar?booking=${source.shoot_booking_id}`} className="block text-xs text-info hover:underline">{source.booking_title ?? "Open shoot"} · {formatDateTime(source.starts_at)} · {titleCase(source.booking_status ?? "")}</Link> : <Link href={`/marketing/content-opportunities?opportunity=${source.content_opportunity_id}`} className="inline-flex items-center gap-1 text-xs text-info hover:underline"><CalendarPlus className="size-3" aria-hidden />Open opportunity to book a shoot</Link>}<p className="text-xs">Customer media permission: <strong>{titleCase(source.permission_status ?? "not recorded")}</strong>{source.permission_expires_at ? ` · expires ${formatDate(source.permission_expires_at)}` : ""}</p><p className="text-xs text-muted-foreground">Allowed uses: {source.permitted_uses.map((use) => USE_LABELS[use] ?? titleCase(use)).join(", ") || "Not recorded"}</p>{source.restrictions && <p className="rounded bg-warning/10 p-2 text-xs">Restrictions: {source.restrictions}</p>}</li>)}</ul>}
        </DrawerSection>
        <DrawerSection title="Links and material"><ul className="space-y-2">{detail.links.map((link) => <li key={link.id} className="flex items-start justify-between gap-3 rounded-md border p-3"><div className="min-w-0 space-y-1"><p className="text-[11px] uppercase tracking-wide text-muted-foreground">{LINK_LABELS[link.kind]}</p><ExternalLinkButton href={link.url}>{link.label}</ExternalLinkButton><p className="text-xs text-muted-foreground">{link.access_state === "confirmed" ? "Access confirmed by staff" : link.access_state === "problem" ? "Access problem — needs attention" : "Access not checked"}</p></div>{editable && <Gated permission="marketing.write"><Button size="sm" variant="ghost" onClick={() => setSelection({ action: "link_remove", targetId: link.id })}>Remove</Button></Gated>}</li>)}</ul>{detail.links.length === 0 && <p className="text-sm text-muted-foreground">Add raw footage, copy, references or a working folder link.</p>}</DrawerSection>
        <DrawerSection title="Readiness notes"><p className="whitespace-pre-wrap text-sm text-muted-foreground">{detail.source_readiness_note || "Coverage and access have not been confirmed yet."}</p></DrawerSection>
      </TabsContent>
      <TabsContent value="versions" className="space-y-4 pt-3">
        <p className="text-xs text-muted-foreground">Each submission keeps its brief and export references. Create a new version when the content changes; file providers may still allow someone to change the linked file.</p>
        {detail.versions.length === 0 && <p className="rounded-md border border-dashed p-5 text-sm text-muted-foreground">No version submitted. Complete preparation and production, then submit a specific export for review.</p>}
        {detail.versions.map((version) => <section key={version.id} className="space-y-3 rounded-lg border p-4"><div className="flex flex-wrap items-center justify-between gap-2"><h3 className="text-sm font-semibold">Version {version.version_no} · {version.export_label}</h3>{detail.approved_version_id === version.id && <TonePill label="Approved version" tone="success" />}</div><p className="text-xs text-muted-foreground">Submitted by {names.get(version.submitted_by) ?? "Staff member"} · {formatDateTime(version.submitted_at)}</p><div className="flex flex-wrap gap-4"><ExternalLinkButton href={version.review_url}>Open review</ExternalLinkButton><ExternalLinkButton href={version.final_url}>Open export</ExternalLinkButton></div>{version.notes && <p className="whitespace-pre-wrap text-sm">{version.notes}</p>}<details className="text-xs"><summary className="cursor-pointer font-medium">Brief at submission</summary><div className="mt-2 space-y-2 text-muted-foreground">{Object.entries(version.brief_snapshot).map(([key, value]) => value ? <p key={key} className="whitespace-pre-wrap"><strong>{titleCase(key)}:</strong> {value}</p> : null)}</div></details>{detail.reviews.filter((review) => review.version_id === version.id).map((review) => <div key={review.id} className="rounded-md bg-muted/30 p-3"><p className="text-xs font-semibold">{review.decision === "approved" ? "Approved" : "Changes requested"} · {names.get(review.reviewer_id) ?? "Reviewer"} · {formatDateTime(review.reviewed_at)}</p><p className="mt-1 whitespace-pre-wrap text-sm">{review.notes}</p></div>)}</section>)}
      </TabsContent>
      <TabsContent value="publishing" className="space-y-4 pt-3">
        <div className="flex flex-wrap items-center justify-between gap-3"><p className="max-w-md text-xs text-muted-foreground">One plan per channel/account release. Dates can be planned before approval; scheduling and publication require an approved version.</p><Gated permission="marketing.write"><Button size="sm" onClick={() => setSelection({ action: "publication_plan" })} disabled={detail.condition === "cancelled"}><Plus className="size-3.5" aria-hidden />Add release plan</Button></Gated></div>
        {detail.publications.length === 0 && <p className="rounded-md border border-dashed p-5 text-sm text-muted-foreground">Unscheduled. Add the first channel release plan; approval alone does not mark this creative as published.</p>}
        {detail.publications.map((pub) => <section key={pub.id} className="space-y-3 rounded-lg border p-4"><div className="flex flex-wrap items-center justify-between gap-2"><h3 className="text-sm font-semibold">{CHANNEL_LABELS[pub.channel] ?? pub.channel} · {pub.account_label}</h3><StatusPill map={PUBLICATION_META} value={pub.status} /></div><p className="text-xs text-muted-foreground">{USE_LABELS[pub.intended_use]} · Target {pub.target_date ? formatDate(pub.target_date) : "not set"}</p>{pub.scheduled_at && <p className="text-xs">Scheduled {formatDateTime(pub.scheduled_at)} · {pub.scheduling_method}</p>}{pub.published_at && <p className="text-xs">Published {formatDateTime(pub.published_at)}</p>}{pub.live_url && <ExternalLinkButton href={pub.live_url}>Open live post</ExternalLinkButton>}{pub.cancellation_reason && <p className="text-xs">Cancelled: {pub.cancellation_reason}</p>}{pub.external_action_required && <div className="space-y-2 rounded-md border border-warning/30 bg-warning/5 p-3"><p className="text-xs font-medium">External follow-up required: {pub.external_action_note || "Check and cancel/remove the affected external post as needed."}</p><Gated permission="creative.publish"><Button size="sm" variant="outline" onClick={() => setSelection({ action: "external_action", targetId: pub.id })}>Record action taken</Button></Gated></div>}
          {!["published", "cancelled"].includes(pub.status) && <div className="flex flex-wrap gap-2"><Gated permission="marketing.write"><Button size="sm" variant="outline" onClick={() => setSelection({ action: "publication_plan", targetId: pub.id })} disabled={pub.status === "scheduled"}>Edit plan</Button></Gated><Gated permission="creative.publish"><Button size="sm" variant="outline" disabled={!detail.approved_version_id || detail.condition !== "active"} onClick={() => setSelection({ action: "publication_schedule", targetId: pub.id })}>{pub.status === "scheduled" ? "Reschedule" : "Record scheduled"}</Button></Gated><Gated permission="creative.publish"><Button size="sm" disabled={!detail.approved_version_id || detail.condition !== "active"} onClick={() => setSelection({ action: "publication_publish", targetId: pub.id })}>Record published</Button></Gated><Gated permission="creative.publish"><Button size="sm" variant="ghost" onClick={() => setSelection({ action: "publication_cancel", targetId: pub.id })}>Cancel release</Button></Gated></div>}
        </section>)}
      </TabsContent>
      <TabsContent value="activity" className="space-y-3 pt-3"><p className="text-xs text-muted-foreground">Recorded changes and decisions, newest first.</p><ol className="divide-y rounded-lg border">{detail.events.map((event) => <li key={event.id} className="space-y-1 p-3"><p className="text-sm font-medium">{titleCase(event.action)}</p><p className="text-xs text-muted-foreground">{names.get(event.actor_id) ?? "Staff member"} · {formatDateTime(event.occurred_at)}</p>{typeof event.data.reason === "string" && <p className="whitespace-pre-wrap text-xs">{event.data.reason}</p>}{typeof event.data.notes === "string" && <p className="whitespace-pre-wrap text-xs">{event.data.notes}</p>}</li>)}</ol></TabsContent>
    </Tabs>
    {editing && <EditCreativeDialog detail={detail} options={options} onClose={() => setEditing(false)} />}
    {selection && <CreativeActionDialog key={`${selection.action}:${selection.targetId ?? ""}`} detail={detail} options={options} selection={selection} onClose={() => setSelection(null)} />}
  </RecordDrawer>;
}
